version: "3"
services:
  cm:
    build:
      context: ./cm
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    external_links:
         - rabbit
    networks:
         - hotmaps_cm-net
networks:
 hotmaps_cm-net:
   external: true




