version: "3"
services:
  cm:
    build:
      context: ./cm
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5001
    external_links:
      - rabbit
    networks:
      - hotmaps-toolbox-service_cm-net
    volumes:
      - /var/tmp:/var/tmp

networks:
  hotmaps-toolbox-service_cm-net:
    external: true



